[general]
#import = ["~/.config/alacritty/themes/atom_one_light.toml"]
import = ["~/.config/alacritty/themes/night_owlish_light.toml"]
#import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

[font]
size = 10

[font.bold]
family = "JetBrains Mono"

[font.bold_italic]
family = "JetBrains Mono"

[font.italic]
family = "JetBrains Mono"

[font.normal]
family = "JetBrains Mono"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "None"
key = "Pause"
mods = "Control"

[[keyboard.bindings]]
action = "None"
key = "Pause"
mods = "Alt"

[[keyboard.bindings]]
action = "None"
key = "Pause"
mods = "Shift"

[[keyboard.bindings]]
action = "None"
key = "Pause"

[window.padding]
x = 5
y = 3
