[font]
size = 10

[font.bold]
family = "JetBrains Mono"

[font.bold_italic]
family = "JetBrains Mono"

[font.italic]
family = "JetBrains Mono"

[font.normal]
family = "JetBrains Mono"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "None"
key = "Pause"

[[keyboard.bindings]]
action = "None"
key = "Pause"
mods = "Shift"

[window.padding]
x = 5
y = 3

[colors.bright]
black = "#7a8181"
blue = "#5ca7e4"
cyan = "#00c990"
green = "#49d0c5"
magenta = "#697098"
red = "#f76e6e"
white = "#989fb1"
yellow = "#dac26b"

[colors.cursor]
cursor = "#403f53"
text = "#fbfbfb"

[colors.normal]
black = "#011627"
blue = "#4876d6"
cyan = "#08916a"
green = "#2aa298"
magenta = "#403f53"
red = "#d3423e"
white = "#7a8181"
yellow = "#daaa01"

[colors.primary]
background = "#ffffff"
foreground = "#403f53"

[colors.selection]
background = "#f2f2f2"
text = "#403f53"

